### ISSUE TITLE
Missing class DiverseLinearLayoutManager

### ISSUE THREAD

**Issue by jairobjunior** [Trading212/sticky-headers#5]
Fist off, thank you for your contribution.

I am trying to execute the demo project, but it seems that `DiverseLinearLayoutManager` is missing.

It's being used inside of `BaseActivity.kt`. Is `LinearLayoutManager` enough?

**Comment by dragoncodes** [comment]
Hello, thank you for trying out the library!

`DiverseLinearLayoutManager` comes from `'com.trading212:diverse-recycler-adapter'` which is a dependency of the `demo` project and is used only to ease the creating of examples.

If you checkout the repo and run the `demo` project it should resolve all dependencies. If you want to create your own project with sticky headers, you don't need to use `DiverseRecyclerAdapter ` or `DiverseLinearLayoutManager`, as the StickyHeader library itself does not depend on the DiverseRecyclerAdapter library.

So, yes, `LinearLayoutManager` will do the job, although we've only tested with a `VERTICAL` orientation.
